services:
  pemweb_uas:
    build: ./php
    image: pemweb_php_uas:latest
    container_name: pemweb_uas
    hostname: "pemweb_uas"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx_pemweb_uas:
    build: ./nginx
    image: nginx_pemweb_uas:latest
    container_name: nginx_pemweb_uas
    hostname: "nginx_pemweb_uas"
    ports:
      - "87:87"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pemweb_uas